version: "2"
run:
  tests: false
  timeout: 1m
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - gocritic
    - gosec
    - misspell
    - revive
    - unparam
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: examples/
      - linters:
          - errcheck
        path: _test\.go
      - linters:
          - errcheck
          - unused
        path: _mock\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
