linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gosimple
    - unused

run:
  timeout: 1m
  tests: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: _mock\.go
      linters:
        - errcheck
        - unused

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
