linters:
  enable:
    - gofmt
    - govet
    # - dupl TODO: enable
    - gocritic
    - errcheck
    - staticcheck
    - ineffassign
    - typecheck
    - gosimple
    - misspell
    - unparam
    - unused
    # - gosec TODO: enable
    - revive

run:
  timeout: 1m
  tests: false

issues:
  exclude-rules:
    - path: examples/
      linters:
        - gosec
    - path: _test\.go
      linters:
        - errcheck
    - path: _mock\.go
      linters:
        - errcheck
        - unused

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
