name: XRPL-GO Lint and Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]
jobs:
  build:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.23'
        cache: true
    
    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.8
      
    - name: Run linter
      run: make lint
      
    - name: Run tests
      run: make test-ci